actors:
  hoshikawa:
    image_url: https://www.gravatar.com/avatar/4228f869e90f20d04ce6d4005286c623?s=300
    name: hoshikawa
  hidetake:
    image_url: https://www.gravatar.com/avatar/c50eca9d63f3a6179ab14645cf2dc1ea?s=300
    name: hidetake
author: hidetake
description: 外気浴しながらあれこれ話す
description_long: 外気浴しながらあれこれ話す
email: shidetake+gaikiyokufm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-220304477-1
google_analytics_ga4: G-EXSYYCEXY1
hashtag: gaikiyokufm
itunes_podcast_url: https://podcasts.apple.com/us/podcast/gaikiyoku-fm/id1598934840
spotify_podcast_url: https://open.spotify.com/show/5u2mO7mjow8n1wrmc5vygH
keywords: sauna,money,tech,technology,gadget
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: gaikiyoku.fm
url: https://gaikiyoku.fm
domain: gaikiyoku.fm
plugins:
  - jekyll-sitemap
