actors:
  hoshikawa:
    image_url: /images/actors/hoshikawa.png
    name: hoshikawa
  hidetake:
    image_url: /images/actors/hidetake.png
    name: hidetake
author: hidetake
description: 外気浴しながらあれこれ話す
description_long: 外気浴しながらあれこれ話す
email: shidetake+gaikiyokufm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: gaikiyokufm
itunes_podcast_url:
keywords: sauna,money,tech,technology,gadget
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: gaikiyoku.fm
url: https://gaikiyoku.fm
domain: gaikiyoku.fm
